---
driver:
  name: docker
  privileged: true

driver_config:
  provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  require_chef_omnibus: false

provision_command:

platforms:
- name: ubuntu-14.04
  provisioner:               
    name: chef_solo          
    chef_omnibus_root: '/usr'
  run_list:
    - recipe[quagga-test::default_a]
    - recipe[quagga-test::default_b]
  busser:                    
    ruby_bindir: /usr/bin

suites:
  - name: install_quagga
    excludes: []
    driver:
      provision_command:
        - wget https://objects-us-west-1.dream.io/public_github/docker/dpkg/quagga_0.99.23.1-1%2Bcl3u1_trusty_amd64.deb
        - sudo dpkg -i quagga_0.99.23.1-1%2Bcl3u1_trusty_amd64.deb
