---
driver:
  name: docker

platforms:
 - name: ubuntu-14.04
	driver:                                   
    	  box: ubuntu/trusty64                    
   	  box_url: 'ubuntu/trusty64'              
  	  provision: true                         
  	  vagrantfiles: ['test/provision-chef.rb']
	provisioner:                              
  	  name: chef_solo                         
  	  chef_omnibus_root: '/usr'               
        busser:
	  ruby_bindir: /usr/bin
