---
driver:
  name: docker

platforms:
  - name: ubuntu-14.04
    run_list:
            - recipe[quagga-test::default_a]
            - recipe[quagga-test::default_b]
  - name: cumulusnetworks/docker-router
    run_list:
            - recipe[quagga-test::default_a]
            - recipe[quagga-test::default_b]
