---
driver:
  name: docker
  privileged: true

driver_config:
  provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  require_chef_omnibus: false

platforms:
- name: ubuntu-14.04
  provisioner:               
    name: chef_solo          
    chef_omnibus_root: '/usr'
- name: cumulusnetworks/docker_router
  provisioner:               
    name: chef_solo          
    chef_omnibus_root: '/usr'

suites:
  - name: a
    excludes: 
      - ubuntu-14.04
    run_list:
      - recipe[quagga-test::default_a]
  - name: b
    run_list:
      - recipe[quagga-test::default_b]
