---
driver:
  name: docker
  privileged: true

platforms:
- name: centos-6.6
- name: ubuntu-14.04
  run_list:
    - recipe[quagga-test::default_a]
    - recipe[quagga-test::default_b]
  driver:
    run_command: ['test/provision-chef.rb']
  provisioner:               
    name: chef_solo          
    chef_omnibus_root: '/usr'
  busser:                    
    ruby_bindir: /usr/bin
